FROM pytorch/pytorch:2.2.0-cuda11.8-cudnn8-runtime



WORKDIR /memeGPT


COPY . /memeGPT


RUN pip install --no-cache-dir -r requirements.txt


RUN chmod +x /memeGPT/scripts/train.py


ENTRYPOINT ["python", "-m", "memeGPT.scripts.train"]
CMD ["--help"]